title: Página de Edgar
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://edgargomezlozano.github.io

aux_links:
  Template Repository: https://github.com/edgargomezlozano.github.io/Página de Edgar
